
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.QinShi table.
    /// </summary>
    [Table(Name="dbo.QinShi")]
    public partial class QinShi
        : LinqEntityBase
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="QinShi"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public QinShi()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _trueid = default(long);

        /// <summary>
        /// Gets the trueid column value.
        /// </summary>
        [Column(Name="trueid", Storage="_trueid", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long Trueid
        {
            get { return _trueid; }
            set
            {
                if (_trueid != value)
                {
                    OnTrueidChanging(value);
                    OnPropertyChanging("Trueid");
                    _trueid = value;
                    OnPropertyChanged("Trueid");
                    OnTrueidChanged();
                }
            }
        }
        
        private Nullable<long> _id;

        /// <summary>
        /// Gets or sets the id column value.
        /// </summary>
        [Column(Name="id", Storage="_id", DbType="bigint")]
        public Nullable<long> Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _id = value;
                    OnPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        
        private string _qinShiMember;

        /// <summary>
        /// Gets or sets the QinShi column value.
        /// </summary>
        [Column(Name="QinShi", Storage="_qinShiMember", DbType="nvarchar(50) NOT NULL", CanBeNull=false)]
        public string QinShiMember
        {
            get { return _qinShiMember; }
            set
            {
                if (_qinShiMember != value)
                {
                    OnQinShiMemberChanging(value);
                    OnPropertyChanging("QinShiMember");
                    _qinShiMember = value;
                    OnPropertyChanged("QinShiMember");
                    OnQinShiMemberChanged();
                }
            }
        }
        
        private long _school;

        /// <summary>
        /// Gets or sets the School column value.
        /// </summary>
        [Column(Name="School", Storage="_school", DbType="bigint NOT NULL", CanBeNull=false)]
        public long School
        {
            get { return _school; }
            set
            {
                if (_school != value)
                {
                    OnSchoolChanging(value);
                    OnPropertyChanging("School");
                    _school = value;
                    OnPropertyChanged("School");
                    OnSchoolChanged();
                }
            }
        }
        
        private int _schoolClass;

        /// <summary>
        /// Gets or sets the SchoolClass column value.
        /// </summary>
        [Column(Name="SchoolClass", Storage="_schoolClass", DbType="int NOT NULL", CanBeNull=false)]
        public int SchoolClass
        {
            get { return _schoolClass; }
            set
            {
                if (_schoolClass != value)
                {
                    OnSchoolClassChanging(value);
                    OnPropertyChanging("SchoolClass");
                    _schoolClass = value;
                    OnPropertyChanged("SchoolClass");
                    OnSchoolClassChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Trueid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTrueidChanging(long value);
        /// <summary>Called after Trueid has Changed.</summary>
        partial void OnTrueidChanged();
        /// <summary>Called when Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(Nullable<long> value);
        /// <summary>Called after Id has Changed.</summary>
        partial void OnIdChanged();
        /// <summary>Called when QinShiMember is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnQinShiMemberChanging(string value);
        /// <summary>Called after QinShiMember has Changed.</summary>
        partial void OnQinShiMemberChanged();
        /// <summary>Called when School is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnSchoolChanging(long value);
        /// <summary>Called after School has Changed.</summary>
        partial void OnSchoolChanged();
        /// <summary>Called when SchoolClass is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnSchoolClassChanging(int value);
        /// <summary>Called after SchoolClass has Changed.</summary>
        partial void OnSchoolClassChanged();
        #endregion
        
    }
}

