<?xml version="1.0" encoding="utf-8"?>
<Database Title="CHSNS.Database" Class="CHSNSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=CHSNS.Database;Integrated Security=True" SettingsObjectTitle="CHSNS.SQLServerImplement.Properties.Settings" SettingsPropertyTitle="CHSNS_DatabaseConnectionString1" Provider="System.Data.SqlClient" />
  
</Database>