var __cultureInfo={"name":"zh-CN",
"numberFormat":{"CurrencyDecimalDigits":2,
"CurrencyDecimalSeparator":".",
"IsReadOnly":true,
"CurrencyGroupSizes":[3],
"NumberGroupSizes":[3],
"PercentGroupSizes":[3],
"CurrencyGroupSeparator":",",
"CurrencySymbol":"￥",
"NaNSymbol":"非数字",
"CurrencyNegativePattern":2,
"NumberNegativePattern":1,
"PercentPositivePattern":1,
"PercentNegativePattern":1,
"NegativeInfinitySymbol":"负无穷大",
"NegativeSign":"-",
"NumberDecimalDigits":2,
"NumberDecimalSeparator":".",
"NumberGroupSeparator":",",
"CurrencyPositivePattern":0,
"PositiveInfinitySymbol":"正无穷大",
"PositiveSign":"+",
"PercentDecimalDigits":2,
"PercentDecimalSeparator":".",
"PercentGroupSeparator":",",
"PercentSymbol":"%",
"PerMilleSymbol":"‰",
"NativeDigits":["0","1","2","3","4","5","6","7","8","9"],
"DigitSubstitution":1
},
	"dateTimeFormat":{"AMDesignator":"上午",
"Calendar":{"MinSupportedDateTime":"\/Date(-62135578800000)\/",
	"MaxSupportedDateTime":"\/Date(253402300799999)\/",
	"AlgorithmType":1,"CalendarType":1,"Eras":[1],"TwoDigitYearMax":2029,"IsReadOnly":true},
"DateSeparator":"/",
"FirstDayOfWeek":0,"CalendarWeekRule":0,
"FullDateTimePattern":"yyyy年M月d日 H:mm:ss",
"LongDatePattern":"yyyy年M月d日",
"LongTimePattern":"H:mm:ss","MonthDayPattern":"M月d日",
"PMDesignator":"下午",
"RFC1123Pattern":"ddd, dd MMM yyyy HH:mm:ss GMT",
"ShortDatePattern":"yyyy/M/d","ShortTimePattern":"H:mm",
"SortableDateTimePattern":"yyyy-MM-ddTHH:mm:ss",
"TimeSeparator":":",
"UniversalSortableDateTimePattern":"yyyy-MM-dd HH:mm:ssZ",
"YearMonthPattern":"yyyy年M月",
"AbbreviatedDayNames":["日","一","二","三","四","五","六"],
"ShortestDayNames":["日","一","二","三","四","五","六"],
"DayNames":["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
"AbbreviatedMonthNames":["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""],
"MonthNames":["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""],
"IsReadOnly":true,
"NativeCalendarName":"公历",
"AbbreviatedMonthGenitiveNames":["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""],
"MonthGenitiveNames":["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""]
}
	};Sys.CultureInfo.CurrentCulture=__cultureInfo;delete __cultureInfo;