
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.ContactInformation table.
    /// </summary>
    [Table(Name="dbo.ContactInformation")]
    public partial class ContactInformation
        : LinqEntityBase
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactInformation"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public ContactInformation()
        {
            OnCreated();
            _profile = default(EntityRef<Profile>);
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _userid;

        /// <summary>
        /// Gets or sets the userid column value.
        /// </summary>
        [Column(Name="userid", Storage="_userid", DbType="bigint NOT NULL", IsPrimaryKey=true, CanBeNull=false)]
        public long Userid
        {
            get { return _userid; }
            set
            {
                if (_userid != value)
                {
                    if (_profile.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnUseridChanging(value);
                    OnPropertyChanging("Userid");
                    _userid = value;
                    OnPropertyChanged("Userid");
                    OnUseridChanged();
                }
            }
        }
        
        private string _address;

        /// <summary>
        /// Gets or sets the Address column value.
        /// </summary>
        [Column(Name="Address", Storage="_address", DbType="nvarchar(100)")]
        public string Address
        {
            get { return _address; }
            set
            {
                if (_address != value)
                {
                    OnAddressChanging(value);
                    OnPropertyChanging("Address");
                    _address = value;
                    OnPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }
        
        private string _qQ;

        /// <summary>
        /// Gets or sets the QQ column value.
        /// </summary>
        [Column(Name="QQ", Storage="_qQ", DbType="nvarchar(50)")]
        public string QQ
        {
            get { return _qQ; }
            set
            {
                if (_qQ != value)
                {
                    OnQQChanging(value);
                    OnPropertyChanging("QQ");
                    _qQ = value;
                    OnPropertyChanged("QQ");
                    OnQQChanged();
                }
            }
        }
        
        private string _msn;

        /// <summary>
        /// Gets or sets the Msn column value.
        /// </summary>
        [Column(Name="Msn", Storage="_msn", DbType="nvarchar(50)")]
        public string Msn
        {
            get { return _msn; }
            set
            {
                if (_msn != value)
                {
                    OnMsnChanging(value);
                    OnPropertyChanging("Msn");
                    _msn = value;
                    OnPropertyChanged("Msn");
                    OnMsnChanged();
                }
            }
        }
        
        private string _wangWang;

        /// <summary>
        /// Gets or sets the WangWang column value.
        /// </summary>
        [Column(Name="WangWang", Storage="_wangWang", DbType="nvarchar(50)")]
        public string WangWang
        {
            get { return _wangWang; }
            set
            {
                if (_wangWang != value)
                {
                    OnWangWangChanging(value);
                    OnPropertyChanging("WangWang");
                    _wangWang = value;
                    OnPropertyChanged("WangWang");
                    OnWangWangChanged();
                }
            }
        }
        
        private string _neteasePop;

        /// <summary>
        /// Gets or sets the NeteasePop column value.
        /// </summary>
        [Column(Name="NeteasePop", Storage="_neteasePop", DbType="nvarchar(50)")]
        public string NeteasePop
        {
            get { return _neteasePop; }
            set
            {
                if (_neteasePop != value)
                {
                    OnNeteasePopChanging(value);
                    OnPropertyChanging("NeteasePop");
                    _neteasePop = value;
                    OnPropertyChanged("NeteasePop");
                    OnNeteasePopChanged();
                }
            }
        }
        
        private string _uC;

        /// <summary>
        /// Gets or sets the UC column value.
        /// </summary>
        [Column(Name="UC", Storage="_uC", DbType="nvarchar(50)")]
        public string UC
        {
            get { return _uC; }
            set
            {
                if (_uC != value)
                {
                    OnUCChanging(value);
                    OnPropertyChanging("UC");
                    _uC = value;
                    OnPropertyChanged("UC");
                    OnUCChanged();
                }
            }
        }
        
        private string _telphone;

        /// <summary>
        /// Gets or sets the Telphone column value.
        /// </summary>
        [Column(Name="Telphone", Storage="_telphone", DbType="nvarchar(50)")]
        public string Telphone
        {
            get { return _telphone; }
            set
            {
                if (_telphone != value)
                {
                    OnTelphoneChanging(value);
                    OnPropertyChanging("Telphone");
                    _telphone = value;
                    OnPropertyChanged("Telphone");
                    OnTelphoneChanged();
                }
            }
        }
        
        private string _mobiephone;

        /// <summary>
        /// Gets or sets the Mobiephone column value.
        /// </summary>
        [Column(Name="Mobiephone", Storage="_mobiephone", DbType="nvarchar(50)")]
        public string Mobiephone
        {
            get { return _mobiephone; }
            set
            {
                if (_mobiephone != value)
                {
                    OnMobiephoneChanging(value);
                    OnPropertyChanging("Mobiephone");
                    _mobiephone = value;
                    OnPropertyChanged("Mobiephone");
                    OnMobiephoneChanged();
                }
            }
        }
        
        private string _webSite;

        /// <summary>
        /// Gets or sets the WebSite column value.
        /// </summary>
        [Column(Name="WebSite", Storage="_webSite", DbType="nvarchar(100)")]
        public string WebSite
        {
            get { return _webSite; }
            set
            {
                if (_webSite != value)
                {
                    OnWebSiteChanging(value);
                    OnPropertyChanging("WebSite");
                    _webSite = value;
                    OnPropertyChanged("WebSite");
                    OnWebSiteChanged();
                }
            }
        }
        
        private byte _tellMethod;

        /// <summary>
        /// Gets or sets the TellMethod column value.
        /// </summary>
        [Column(Name="TellMethod", Storage="_tellMethod", DbType="tinyint NOT NULL", CanBeNull=false)]
        public byte TellMethod
        {
            get { return _tellMethod; }
            set
            {
                if (_tellMethod != value)
                {
                    OnTellMethodChanging(value);
                    OnPropertyChanging("TellMethod");
                    _tellMethod = value;
                    OnPropertyChanged("TellMethod");
                    OnTellMethodChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        
        private EntityRef<Profile> _profile;

        /// <summary>
        /// Gets or sets the Profile association.
        /// </summary>
        [Association(Name="FK_ContactInformation_Account", Storage="_profile", ThisKey="Userid", OtherKey="UserId", IsForeignKey=true)]
        public Profile Profile
        {
            get { return _profile.Entity; }
            set
            {
                Profile previousValue = _profile.Entity;
                if (previousValue != value || _profile.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("Profile");
                    if (previousValue != null)
                    {
                        _profile.Entity = null;
                        previousValue.ContactInformation = null;
                    }
                    _profile.Entity = value;
                    if (value != null)
                    {
                        value.ContactInformation = this;
                        _userid = value.UserId;
                    }
                    else
                    {
                        _userid = default(long);
                    }
                    OnPropertyChanged("Profile");
                }
            }
        }
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Userid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUseridChanging(long value);
        /// <summary>Called after Userid has Changed.</summary>
        partial void OnUseridChanged();
        /// <summary>Called when Address is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnAddressChanging(string value);
        /// <summary>Called after Address has Changed.</summary>
        partial void OnAddressChanged();
        /// <summary>Called when QQ is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnQQChanging(string value);
        /// <summary>Called after QQ has Changed.</summary>
        partial void OnQQChanged();
        /// <summary>Called when Msn is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnMsnChanging(string value);
        /// <summary>Called after Msn has Changed.</summary>
        partial void OnMsnChanged();
        /// <summary>Called when WangWang is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnWangWangChanging(string value);
        /// <summary>Called after WangWang has Changed.</summary>
        partial void OnWangWangChanged();
        /// <summary>Called when NeteasePop is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnNeteasePopChanging(string value);
        /// <summary>Called after NeteasePop has Changed.</summary>
        partial void OnNeteasePopChanged();
        /// <summary>Called when UC is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUCChanging(string value);
        /// <summary>Called after UC has Changed.</summary>
        partial void OnUCChanged();
        /// <summary>Called when Telphone is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTelphoneChanging(string value);
        /// <summary>Called after Telphone has Changed.</summary>
        partial void OnTelphoneChanged();
        /// <summary>Called when Mobiephone is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnMobiephoneChanging(string value);
        /// <summary>Called after Mobiephone has Changed.</summary>
        partial void OnMobiephoneChanged();
        /// <summary>Called when WebSite is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnWebSiteChanging(string value);
        /// <summary>Called after WebSite has Changed.</summary>
        partial void OnWebSiteChanged();
        /// <summary>Called when TellMethod is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTellMethodChanging(byte value);
        /// <summary>Called after TellMethod has Changed.</summary>
        partial void OnTellMethodChanged();
        #endregion
        
    }
}

