
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.Event table.
    /// </summary>
    [Table(Name="dbo.Event")]
    public partial class Event
        : LinqEntityBase
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Event"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Event()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _trueid = default(long);

        /// <summary>
        /// Gets the trueid column value.
        /// </summary>
        [Column(Name="trueid", Storage="_trueid", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long Trueid
        {
            get { return _trueid; }
            set
            {
                if (_trueid != value)
                {
                    OnTrueidChanging(value);
                    OnPropertyChanging("Trueid");
                    _trueid = value;
                    OnPropertyChanged("Trueid");
                    OnTrueidChanged();
                }
            }
        }
        
        private Nullable<long> _id;

        /// <summary>
        /// Gets or sets the id column value.
        /// </summary>
        [Column(Name="id", Storage="_id", DbType="bigint")]
        public Nullable<long> Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _id = value;
                    OnPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        
        private long _fromid;

        /// <summary>
        /// Gets or sets the fromid column value.
        /// </summary>
        [Column(Name="fromid", Storage="_fromid", DbType="bigint NOT NULL", CanBeNull=false)]
        public long Fromid
        {
            get { return _fromid; }
            set
            {
                if (_fromid != value)
                {
                    OnFromidChanging(value);
                    OnPropertyChanging("Fromid");
                    _fromid = value;
                    OnPropertyChanged("Fromid");
                    OnFromidChanged();
                }
            }
        }
        
        private long _toid;

        /// <summary>
        /// Gets or sets the toid column value.
        /// </summary>
        [Column(Name="toid", Storage="_toid", DbType="bigint NOT NULL", CanBeNull=false)]
        public long Toid
        {
            get { return _toid; }
            set
            {
                if (_toid != value)
                {
                    OnToidChanging(value);
                    OnPropertyChanging("Toid");
                    _toid = value;
                    OnPropertyChanged("Toid");
                    OnToidChanged();
                }
            }
        }
        
        private System.DateTime _addtime;

        /// <summary>
        /// Gets or sets the Addtime column value.
        /// </summary>
        [Column(Name="Addtime", Storage="_addtime", DbType="smalldatetime NOT NULL", CanBeNull=false)]
        public System.DateTime Addtime
        {
            get { return _addtime; }
            set
            {
                if (_addtime != value)
                {
                    OnAddtimeChanging(value);
                    OnPropertyChanging("Addtime");
                    _addtime = value;
                    OnPropertyChanged("Addtime");
                    OnAddtimeChanged();
                }
            }
        }
        
        private int _type;

        /// <summary>
        /// Gets or sets the type column value.
        /// </summary>
        [Column(Name="type", Storage="_type", DbType="int NOT NULL", CanBeNull=false)]
        public int Type
        {
            get { return _type; }
            set
            {
                if (_type != value)
                {
                    OnTypeChanging(value);
                    OnPropertyChanging("Type");
                    _type = value;
                    OnPropertyChanged("Type");
                    OnTypeChanged();
                }
            }
        }
        
        private string _application;

        /// <summary>
        /// Gets or sets the Application column value.
        /// </summary>
        [Column(Name="Application", Storage="_application", DbType="nvarchar(50)")]
        public string Application
        {
            get { return _application; }
            set
            {
                if (_application != value)
                {
                    OnApplicationChanging(value);
                    OnPropertyChanging("Application");
                    _application = value;
                    OnPropertyChanged("Application");
                    OnApplicationChanged();
                }
            }
        }
        
        private Nullable<long> _actionid;

        /// <summary>
        /// Gets or sets the Actionid column value.
        /// </summary>
        [Column(Name="Actionid", Storage="_actionid", DbType="bigint")]
        public Nullable<long> Actionid
        {
            get { return _actionid; }
            set
            {
                if (_actionid != value)
                {
                    OnActionidChanging(value);
                    OnPropertyChanging("Actionid");
                    _actionid = value;
                    OnPropertyChanged("Actionid");
                    OnActionidChanged();
                }
            }
        }
        
        private string _strext1;

        /// <summary>
        /// Gets or sets the Strext1 column value.
        /// </summary>
        [Column(Name="Strext1", Storage="_strext1", DbType="nvarchar(4000)")]
        public string Strext1
        {
            get { return _strext1; }
            set
            {
                if (_strext1 != value)
                {
                    OnStrext1Changing(value);
                    OnPropertyChanging("Strext1");
                    _strext1 = value;
                    OnPropertyChanged("Strext1");
                    OnStrext1Changed();
                }
            }
        }
        
        private string _strext2;

        /// <summary>
        /// Gets or sets the Strext2 column value.
        /// </summary>
        [Column(Name="Strext2", Storage="_strext2", DbType="nvarchar(4000)")]
        public string Strext2
        {
            get { return _strext2; }
            set
            {
                if (_strext2 != value)
                {
                    OnStrext2Changing(value);
                    OnPropertyChanging("Strext2");
                    _strext2 = value;
                    OnPropertyChanged("Strext2");
                    OnStrext2Changed();
                }
            }
        }
        
        private string _strext3;

        /// <summary>
        /// Gets or sets the Strext3 column value.
        /// </summary>
        [Column(Name="Strext3", Storage="_strext3", DbType="nvarchar(4000)")]
        public string Strext3
        {
            get { return _strext3; }
            set
            {
                if (_strext3 != value)
                {
                    OnStrext3Changing(value);
                    OnPropertyChanging("Strext3");
                    _strext3 = value;
                    OnPropertyChanged("Strext3");
                    OnStrext3Changed();
                }
            }
        }
        
        private Nullable<long> _numext1;

        /// <summary>
        /// Gets or sets the Numext1 column value.
        /// </summary>
        [Column(Name="Numext1", Storage="_numext1", DbType="bigint")]
        public Nullable<long> Numext1
        {
            get { return _numext1; }
            set
            {
                if (_numext1 != value)
                {
                    OnNumext1Changing(value);
                    OnPropertyChanging("Numext1");
                    _numext1 = value;
                    OnPropertyChanged("Numext1");
                    OnNumext1Changed();
                }
            }
        }
        
        private Nullable<long> _numext2;

        /// <summary>
        /// Gets or sets the Numext2 column value.
        /// </summary>
        [Column(Name="Numext2", Storage="_numext2", DbType="bigint")]
        public Nullable<long> Numext2
        {
            get { return _numext2; }
            set
            {
                if (_numext2 != value)
                {
                    OnNumext2Changing(value);
                    OnPropertyChanging("Numext2");
                    _numext2 = value;
                    OnPropertyChanged("Numext2");
                    OnNumext2Changed();
                }
            }
        }
        
        private Nullable<long> _numext3;

        /// <summary>
        /// Gets or sets the Numext3 column value.
        /// </summary>
        [Column(Name="Numext3", Storage="_numext3", DbType="bigint")]
        public Nullable<long> Numext3
        {
            get { return _numext3; }
            set
            {
                if (_numext3 != value)
                {
                    OnNumext3Changing(value);
                    OnPropertyChanging("Numext3");
                    _numext3 = value;
                    OnPropertyChanged("Numext3");
                    OnNumext3Changed();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Trueid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTrueidChanging(long value);
        /// <summary>Called after Trueid has Changed.</summary>
        partial void OnTrueidChanged();
        /// <summary>Called when Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(Nullable<long> value);
        /// <summary>Called after Id has Changed.</summary>
        partial void OnIdChanged();
        /// <summary>Called when Fromid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFromidChanging(long value);
        /// <summary>Called after Fromid has Changed.</summary>
        partial void OnFromidChanged();
        /// <summary>Called when Toid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnToidChanging(long value);
        /// <summary>Called after Toid has Changed.</summary>
        partial void OnToidChanged();
        /// <summary>Called when Addtime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnAddtimeChanging(System.DateTime value);
        /// <summary>Called after Addtime has Changed.</summary>
        partial void OnAddtimeChanged();
        /// <summary>Called when Type is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTypeChanging(int value);
        /// <summary>Called after Type has Changed.</summary>
        partial void OnTypeChanged();
        /// <summary>Called when Application is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnApplicationChanging(string value);
        /// <summary>Called after Application has Changed.</summary>
        partial void OnApplicationChanged();
        /// <summary>Called when Actionid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnActionidChanging(Nullable<long> value);
        /// <summary>Called after Actionid has Changed.</summary>
        partial void OnActionidChanged();
        /// <summary>Called when Strext1 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnStrext1Changing(string value);
        /// <summary>Called after Strext1 has Changed.</summary>
        partial void OnStrext1Changed();
        /// <summary>Called when Strext2 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnStrext2Changing(string value);
        /// <summary>Called after Strext2 has Changed.</summary>
        partial void OnStrext2Changed();
        /// <summary>Called when Strext3 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnStrext3Changing(string value);
        /// <summary>Called after Strext3 has Changed.</summary>
        partial void OnStrext3Changed();
        /// <summary>Called when Numext1 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnNumext1Changing(Nullable<long> value);
        /// <summary>Called after Numext1 has Changed.</summary>
        partial void OnNumext1Changed();
        /// <summary>Called when Numext2 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnNumext2Changing(Nullable<long> value);
        /// <summary>Called after Numext2 has Changed.</summary>
        partial void OnNumext2Changed();
        /// <summary>Called when Numext3 is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnNumext3Changing(Nullable<long> value);
        /// <summary>Called after Numext3 has Changed.</summary>
        partial void OnNumext3Changed();
        #endregion
        
    }
}

