
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.Friend table.
    /// </summary>
    [Table(Name="dbo.Friend")]
    public partial class Friend
        : LinqEntityBase
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Friend"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Friend()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _trueid = default(long);

        /// <summary>
        /// Gets the trueid column value.
        /// </summary>
        [Column(Name="trueid", Storage="_trueid", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long Trueid
        {
            get { return _trueid; }
            set
            {
                if (_trueid != value)
                {
                    OnTrueidChanging(value);
                    OnPropertyChanging("Trueid");
                    _trueid = value;
                    OnPropertyChanged("Trueid");
                    OnTrueidChanged();
                }
            }
        }
        
        private Nullable<long> _id;

        /// <summary>
        /// Gets or sets the id column value.
        /// </summary>
        [Column(Name="id", Storage="_id", DbType="bigint")]
        public Nullable<long> Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _id = value;
                    OnPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        
        private long _fromid;

        /// <summary>
        /// Gets or sets the fromid column value.
        /// </summary>
        [Column(Name="fromid", Storage="_fromid", DbType="bigint NOT NULL", CanBeNull=false)]
        public long Fromid
        {
            get { return _fromid; }
            set
            {
                if (_fromid != value)
                {
                    OnFromidChanging(value);
                    OnPropertyChanging("Fromid");
                    _fromid = value;
                    OnPropertyChanged("Fromid");
                    OnFromidChanged();
                }
            }
        }
        
        private long _toid;

        /// <summary>
        /// Gets or sets the toid column value.
        /// </summary>
        [Column(Name="toid", Storage="_toid", DbType="bigint NOT NULL", CanBeNull=false)]
        public long Toid
        {
            get { return _toid; }
            set
            {
                if (_toid != value)
                {
                    OnToidChanging(value);
                    OnPropertyChanging("Toid");
                    _toid = value;
                    OnPropertyChanged("Toid");
                    OnToidChanged();
                }
            }
        }
        
        private bool _isTrue;

        /// <summary>
        /// Gets or sets the IsTrue column value.
        /// </summary>
        [Column(Name="IsTrue", Storage="_isTrue", DbType="bit NOT NULL", CanBeNull=false)]
        public bool IsTrue
        {
            get { return _isTrue; }
            set
            {
                if (_isTrue != value)
                {
                    OnIsTrueChanging(value);
                    OnPropertyChanging("IsTrue");
                    _isTrue = value;
                    OnPropertyChanged("IsTrue");
                    OnIsTrueChanged();
                }
            }
        }
        
        private bool _isCommon;

        /// <summary>
        /// Gets or sets the IsCommon column value.
        /// </summary>
        [Column(Name="IsCommon", Storage="_isCommon", DbType="bit NOT NULL", CanBeNull=false)]
        public bool IsCommon
        {
            get { return _isCommon; }
            set
            {
                if (_isCommon != value)
                {
                    OnIsCommonChanging(value);
                    OnPropertyChanging("IsCommon");
                    _isCommon = value;
                    OnPropertyChanged("IsCommon");
                    OnIsCommonChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Trueid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTrueidChanging(long value);
        /// <summary>Called after Trueid has Changed.</summary>
        partial void OnTrueidChanged();
        /// <summary>Called when Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(Nullable<long> value);
        /// <summary>Called after Id has Changed.</summary>
        partial void OnIdChanged();
        /// <summary>Called when Fromid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFromidChanging(long value);
        /// <summary>Called after Fromid has Changed.</summary>
        partial void OnFromidChanged();
        /// <summary>Called when Toid is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnToidChanging(long value);
        /// <summary>Called after Toid has Changed.</summary>
        partial void OnToidChanged();
        /// <summary>Called when IsTrue is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIsTrueChanging(bool value);
        /// <summary>Called after IsTrue has Changed.</summary>
        partial void OnIsTrueChanged();
        /// <summary>Called when IsCommon is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIsCommonChanging(bool value);
        /// <summary>Called after IsCommon has Changed.</summary>
        partial void OnIsCommonChanged();
        #endregion
        
    }
}

