
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.ViewData table.
    /// </summary>
    [Table(Name="dbo.ViewData")]
    public partial class ViewData
        : LinqEntityBase
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="ViewData"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public ViewData()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _iD = default(long);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_iD", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    OnIDChanging(value);
                    OnPropertyChanging("ID");
                    _iD = value;
                    OnPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        
        private long _ownerID;

        /// <summary>
        /// Gets or sets the OwnerID column value.
        /// </summary>
        [Column(Name="OwnerID", Storage="_ownerID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long OwnerID
        {
            get { return _ownerID; }
            set
            {
                if (_ownerID != value)
                {
                    OnOwnerIDChanging(value);
                    OnPropertyChanging("OwnerID");
                    _ownerID = value;
                    OnPropertyChanged("OwnerID");
                    OnOwnerIDChanged();
                }
            }
        }
        
        private long _viewerID;

        /// <summary>
        /// Gets or sets the ViewerID column value.
        /// </summary>
        [Column(Name="ViewerID", Storage="_viewerID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long ViewerID
        {
            get { return _viewerID; }
            set
            {
                if (_viewerID != value)
                {
                    OnViewerIDChanging(value);
                    OnPropertyChanging("ViewerID");
                    _viewerID = value;
                    OnPropertyChanged("ViewerID");
                    OnViewerIDChanged();
                }
            }
        }
        
        private string _ipandComputer;

        /// <summary>
        /// Gets or sets the IpandComputer column value.
        /// </summary>
        [Column(Name="IpandComputer", Storage="_ipandComputer", DbType="nvarchar(50)")]
        public string IpandComputer
        {
            get { return _ipandComputer; }
            set
            {
                if (_ipandComputer != value)
                {
                    OnIpandComputerChanging(value);
                    OnPropertyChanging("IpandComputer");
                    _ipandComputer = value;
                    OnPropertyChanged("IpandComputer");
                    OnIpandComputerChanged();
                }
            }
        }
        
        private string _viewPageUrl;

        /// <summary>
        /// Gets or sets the ViewPageUrl column value.
        /// </summary>
        [Column(Name="ViewPageUrl", Storage="_viewPageUrl", DbType="nvarchar(255)")]
        public string ViewPageUrl
        {
            get { return _viewPageUrl; }
            set
            {
                if (_viewPageUrl != value)
                {
                    OnViewPageUrlChanging(value);
                    OnPropertyChanging("ViewPageUrl");
                    _viewPageUrl = value;
                    OnPropertyChanged("ViewPageUrl");
                    OnViewPageUrlChanged();
                }
            }
        }
        
        private string _lastUrl;

        /// <summary>
        /// Gets or sets the LastUrl column value.
        /// </summary>
        [Column(Name="LastUrl", Storage="_lastUrl", DbType="nvarchar(255)")]
        public string LastUrl
        {
            get { return _lastUrl; }
            set
            {
                if (_lastUrl != value)
                {
                    OnLastUrlChanging(value);
                    OnPropertyChanging("LastUrl");
                    _lastUrl = value;
                    OnPropertyChanged("LastUrl");
                    OnLastUrlChanged();
                }
            }
        }
        
        private System.DateTime _viewTime;

        /// <summary>
        /// Gets or sets the ViewTime column value.
        /// </summary>
        [Column(Name="ViewTime", Storage="_viewTime", DbType="datetime NOT NULL", CanBeNull=false)]
        public System.DateTime ViewTime
        {
            get { return _viewTime; }
            set
            {
                if (_viewTime != value)
                {
                    OnViewTimeChanging(value);
                    OnPropertyChanging("ViewTime");
                    _viewTime = value;
                    OnPropertyChanged("ViewTime");
                    OnViewTimeChanged();
                }
            }
        }
        
        private byte _viewClass;

        /// <summary>
        /// Gets or sets the ViewClass column value.
        /// </summary>
        [Column(Name="ViewClass", Storage="_viewClass", DbType="tinyint NOT NULL", CanBeNull=false)]
        public byte ViewClass
        {
            get { return _viewClass; }
            set
            {
                if (_viewClass != value)
                {
                    OnViewClassChanging(value);
                    OnPropertyChanging("ViewClass");
                    _viewClass = value;
                    OnPropertyChanged("ViewClass");
                    OnViewClassChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(long value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when OwnerID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnOwnerIDChanging(long value);
        /// <summary>Called after OwnerID has Changed.</summary>
        partial void OnOwnerIDChanged();
        /// <summary>Called when ViewerID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewerIDChanging(long value);
        /// <summary>Called after ViewerID has Changed.</summary>
        partial void OnViewerIDChanged();
        /// <summary>Called when IpandComputer is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIpandComputerChanging(string value);
        /// <summary>Called after IpandComputer has Changed.</summary>
        partial void OnIpandComputerChanged();
        /// <summary>Called when ViewPageUrl is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewPageUrlChanging(string value);
        /// <summary>Called after ViewPageUrl has Changed.</summary>
        partial void OnViewPageUrlChanged();
        /// <summary>Called when LastUrl is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLastUrlChanging(string value);
        /// <summary>Called after LastUrl has Changed.</summary>
        partial void OnLastUrlChanged();
        /// <summary>Called when ViewTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewTimeChanging(System.DateTime value);
        /// <summary>Called after ViewTime has Changed.</summary>
        partial void OnViewTimeChanged();
        /// <summary>Called when ViewClass is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewClassChanging(byte value);
        /// <summary>Called after ViewClass has Changed.</summary>
        partial void OnViewClassChanged();
        #endregion
        
    }
}

