<?xml version="1.0" encoding="utf-8"?>
<Database Name="sq_menglei" Class="ChAlumnaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHSWORD;Initial Catalog=sq_menglei;Integrated Security=True" SettingsObjectName="ChAlumna.Models.Properties.Settings" SettingsPropertyName="sq_mengleiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="question" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="answer" Type="System.String" DbType="Char(32)" CanBeNull="true" />
      <Column Name="code" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="logintime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="regtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="truepassword" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="trueemail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewData" Member="ViewData">
    <Type Name="ViewData">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ownerid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Viewerid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IpandComputer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewPageUrl" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LastUrl" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ViewTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ViewClass" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Album" Member="Album">
    <Type Name="Album">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Showlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="faceurl" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Application">
    <Type Name="Application">
      <Column Name="id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="shortname" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Folder" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Vision" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Authorid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Edittime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="isSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isTrue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionUrl" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UserCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BasicInformation" Member="BasicInformation">
    <Type Name="BasicInformation">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BirthDay" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Province" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Profile_BasicInformation" Member="Profile" ThisKey="userid" Type="Profile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blogs" Member="Blogs">
    <Type Name="Blogs">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Publish" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WriteName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CommentEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Skin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Css" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MetaKey" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="IsWebServices" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="category">
    <Type Name="category">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="City">
    <Type Name="City">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comment">
    <Type Name="Comment">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Logid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="senderid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsReply" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="istellme" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactInformation" Member="ContactInformation">
    <Type Name="ContactInformation">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Msn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WangWang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NeteasePop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telphone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobiephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WebSite" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TellMethod" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Profile_ContactInformation" Member="Profile" ThisKey="userid" Type="Profile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DelLog" Member="DelLog">
    <Type Name="DelLog">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPost" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Anonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EditTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PushCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DelTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Executerid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Event">
    <Type Name="Event">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="fromid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="toid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Actionid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Strext1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Strext2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Strext3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Numext1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Numext2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Numext3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Field" Member="Field">
    <Type Name="Field">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="istrue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FieldInformation" Member="FieldInformation">
    <Type Name="FieldInformation">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Field" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MiniField" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QinShi" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Field1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Field2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Profile_FieldInformation" Member="Profile" ThisKey="userid" Type="Profile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Friend" Member="Friend">
    <Type Name="Friend">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="fromid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="toid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsTrue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCommon" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Group">
    <Type Name="Group">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="summmary" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateUserid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Publish" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GroupClass" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AdminCount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="JoinLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UserCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaxUserCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MagicBox" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LogoUrl" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Num0" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Other0" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Other1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Other2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsTrue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="categoryid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Group_GroupUser" Member="GroupUser" ThisKey="id" OtherKey="Groupid" Type="GroupUser" />
    </Type>
  </Table>
  <Table Name="dbo.GroupUser" Member="GroupUser">
    <Type Name="GroupUser">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Groupid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsTrue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRss" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Group_GroupUser" Member="Group" ThisKey="Groupid" OtherKey="id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Note">
    <Type Name="Note">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPost" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Anonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PushCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LastCommentUserid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LastCommentTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="istellme" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Log_LogTag" Member="LogTag" OtherKey="logid" Type="LogTag" />
      <Association Name="Log_Push" Member="Push" OtherKey="Logid" Type="Push" />
    </Type>
  </Table>
  <Table Name="dbo.LogTag" Member="LogTag">
    <Type Name="LogTag">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tagid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="logid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Log_LogTag" Member="Note" ThisKey="logid" Type="Note" IsForeignKey="true" />
      <Association Name="Tags_LogTag" Member="Tags" ThisKey="tagid" Type="Tags" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Message">
    <Type Name="Message">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FromId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ToId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SendTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsSee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsFromDel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsToDel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHtml" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MiniField" Member="MiniField">
    <Type Name="MiniField">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalInformation" Member="PersonalInformation">
    <Type Name="PersonalInformation">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoveLike" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveBook" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveMusic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveMovie" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveSports" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveGame" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoveComic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="JoinSociety" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Profile_PersonalInformation" Member="Profile" ThisKey="userid" Type="Profile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photos" Member="Photos">
    <Type Name="Photos">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Albumid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Profile" Member="Profile">
    <Type Name="Profile">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShowText" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ShowTextTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Score" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ShowScore" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DelScore" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MagicBox" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FaceShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BasicInfoShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SchoolInfoShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ContactInfoShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PersonalInfoShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AllShowLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MessageAll" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MessageCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileSizeAll" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileSizeCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FriendAll" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FriendCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsMagicBox" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsStar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Applications" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="Applicationlist" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="AlbumCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="field" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="InField" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Profile_BasicInformation" Member="BasicInformation" OtherKey="userid" Type="BasicInformation" Cardinality="One" />
      <Association Name="Profile_ContactInformation" Member="ContactInformation" OtherKey="userid" Type="ContactInformation" Cardinality="One" />
      <Association Name="Profile_FieldInformation" Member="FieldInformation" OtherKey="userid" Type="FieldInformation" Cardinality="One" />
      <Association Name="Profile_PersonalInformation" Member="PersonalInformation" OtherKey="userid" Type="PersonalInformation" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Province">
    <Type Name="Province">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Push" Member="Push">
    <Type Name="Push">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Logid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PushTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Log_Push" Member="Note" ThisKey="Logid" Type="Note" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QinShi" Member="QinShi">
    <Type Name="QinShi">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QinShi" Member="QinShi1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="School" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SchoolClass" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Services">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="sendtime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Answertime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SuperNote" Member="SuperNote">
    <Type Name="SuperNote">
      <Column Name="trueid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="faceurl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="showlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="systemcategory" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tags">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ReachTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tags_LogTag" Member="LogTag" OtherKey="tagid" Type="LogTag" />
    </Type>
  </Table>
</Database>