<?xml version="1.0" encoding="utf-16"?>
<Database Name="sq_menglei" EntityNamespace="CHSNS.Models" ContextNamespace="CHSNS.Models" Class="CHSNSDBDataContext" EntityBase="LinqEntityBase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=sq_menglei;Integrated Security=True" SettingsObjectName="Properties.Settings" SettingsPropertyName="SqMengleiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(12) NOT NULL" CanBeNull="false" />
      <Column Name="email" Member="Email" Storage="_email" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Member="Password" Storage="_password" Type="System.String" DbType="char(32) NOT NULL" CanBeNull="false" />
      <Column Name="question" Member="Question" Storage="_question" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="answer" Member="Answer" Storage="_answer" Type="System.String" DbType="char(32)" CanBeNull="true" />
      <Column Name="code" Member="Code" Storage="_code" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="logintime" Member="Logintime" Storage="_logintime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="regtime" Member="Regtime" Storage="_regtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="truepassword" Member="Truepassword" Storage="_truepassword" Type="System.String" DbType="char(32) NOT NULL" CanBeNull="false" />
      <Column Name="trueemail" Member="Trueemail" Storage="_trueemail" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Member="Status" Storage="_status" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Album" Member="Album">
    <Type Name="Album">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Showlevel" Member="Showlevel" Storage="_showlevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="Description" Member="Description" Storage="_description" Type="System.String" DbType="nvarchar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Order" Member="Order" Storage="_order" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Member="Location" Storage="_location" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="faceurl" Member="Faceurl" Storage="_faceurl" Type="System.String" DbType="nvarchar(250)" CanBeNull="true" />
      <Column Name="Count" Member="Count" Storage="_count" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Application">
    <Type Name="Application">
      <Column Name="id" Member="Id" Storage="_id" Type="System.String" DbType="varchar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fullname" Member="Fullname" Storage="_fullname" Type="System.String" DbType="nvarchar(60) NOT NULL" CanBeNull="false" />
      <Column Name="shortname" Member="Shortname" Storage="_shortname" Type="System.String" DbType="nvarchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Folder" Member="Folder" Storage="_folder" Type="System.String" DbType="nvarchar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Vision" Member="Vision" Storage="_vision" Type="System.String" DbType="nvarchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="icon" Member="Icon" Storage="_icon" Type="System.String" DbType="nvarchar(250)" CanBeNull="true" />
      <Column Name="Authorid" Member="Authorid" Storage="_authorid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Edittime" Member="Edittime" Storage="_edittime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Member="Description" Storage="_description" Type="System.String" DbType="ntext NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="isSystem" Member="IsSystem" Storage="_isSystem" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="isTrue" Member="IsTrue" Storage="_isTrue" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionUrl" Member="DescriptionUrl" Storage="_descriptionUrl" Type="System.String" DbType="nvarchar(250)" CanBeNull="true" />
      <Column Name="UserCount" Member="UserCount" Storage="_userCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BasicInformation" Member="BasicInformation">
    <Type Name="BasicInformation">
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sex" Member="Sex" Storage="_sex" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="BirthDay" Member="BirthDay" Storage="_birthDay" Type="System.DateTime" DbType="smalldatetime" CanBeNull="true" />
      <Column Name="Province" Member="Province" Storage="_province" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="City" Member="City" Storage="_city" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Association Name="FK_BasicInformation_Profile" Member="Profile" Storage="_profile" ThisKey="Userid" OtherKey="UserId" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blogs" Member="Blogs">
    <Type Name="Blogs">
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateTime" Member="CreateTime" Storage="_createTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubTitle" Member="SubTitle" Storage="_subTitle" Type="System.String" DbType="nvarchar(500)" CanBeNull="true" />
      <Column Name="Publish" Member="Publish" Storage="_publish" Type="System.String" DbType="nvarchar(MAX)" CanBeNull="true" />
      <Column Name="WriteName" Member="WriteName" Storage="_writeName" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CommentEmail" Member="CommentEmail" Storage="_commentEmail" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Skin" Member="Skin" Storage="_skin" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Css" Member="Css" Storage="_css" Type="System.String" DbType="ntext" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MetaKey" Member="MetaKey" Storage="_metaKey" Type="System.String" DbType="nvarchar(400)" CanBeNull="true" />
      <Column Name="IsWebServices" Member="IsWebServices" Storage="_isWebServices" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="PostCount" Member="PostCount" Storage="_postCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Member="CommentCount" Storage="_commentCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Member="TrackBackCount" Storage="_trackBackCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="Category">
    <Type Name="Category">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Storage="_type" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="Count" Member="Count" Storage="_count" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="City">
    <Type Name="City">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Member="Pid" Storage="_pid" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comment">
    <Type Name="Comment">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Logid" Member="Logid" Storage="_logid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="ownerid" Member="Ownerid" Storage="_ownerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="senderid" Member="Senderid" Storage="_senderid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="body" Member="Body" Storage="_body" Type="System.String" DbType="ntext NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsReply" Member="IsReply" Storage="_isReply" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSee" Member="IsSee" Storage="_isSee" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDel" Member="IsDel" Storage="_isDel" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Storage="_type" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="istellme" Member="Istellme" Storage="_istellme" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactInformation" Member="ContactInformation">
    <Type Name="ContactInformation">
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Member="Address" Storage="_address" Type="System.String" DbType="nvarchar(100)" CanBeNull="true" />
      <Column Name="QQ" Member="QQ" Storage="_qQ" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Msn" Member="Msn" Storage="_msn" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="WangWang" Member="WangWang" Storage="_wangWang" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="NeteasePop" Member="NeteasePop" Storage="_neteasePop" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="UC" Member="UC" Storage="_uC" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Telphone" Member="Telphone" Storage="_telphone" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Mobiephone" Member="Mobiephone" Storage="_mobiephone" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="WebSite" Member="WebSite" Storage="_webSite" Type="System.String" DbType="nvarchar(100)" CanBeNull="true" />
      <Column Name="TellMethod" Member="TellMethod" Storage="_tellMethod" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Association Name="FK_ContactInformation_Account" Member="Profile" Storage="_profile" ThisKey="Userid" OtherKey="UserId" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DelLog" Member="DelLog">
    <Type Name="DelLog">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="body" Member="Body" Storage="_body" Type="System.String" DbType="ntext" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPost" Member="IsPost" Storage="_isPost" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="Anonymous" Member="Anonymous" Storage="_anonymous" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Member="AddTime" Storage="_addTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="EditTime" Member="EditTime" Storage="_editTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Member="ViewCount" Storage="_viewCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="PushCount" Member="PushCount" Storage="_pushCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Member="TrackBackCount" Storage="_trackBackCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Member="CommentCount" Storage="_commentCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Member="GroupId" Storage="_groupId" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="DelTime" Member="DelTime" Storage="_delTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Executerid" Member="Executerid" Storage="_executerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Event">
    <Type Name="Event">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="fromid" Member="Fromid" Storage="_fromid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="toid" Member="Toid" Storage="_toid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Storage="_type" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Application" Member="Application" Storage="_application" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Actionid" Member="Actionid" Storage="_actionid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Strext1" Member="Strext1" Storage="_strext1" Type="System.String" DbType="nvarchar(4000)" CanBeNull="true" />
      <Column Name="Strext2" Member="Strext2" Storage="_strext2" Type="System.String" DbType="nvarchar(4000)" CanBeNull="true" />
      <Column Name="Strext3" Member="Strext3" Storage="_strext3" Type="System.String" DbType="nvarchar(4000)" CanBeNull="true" />
      <Column Name="Numext1" Member="Numext1" Storage="_numext1" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Numext2" Member="Numext2" Storage="_numext2" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Numext3" Member="Numext3" Storage="_numext3" Type="System.Int64" DbType="bigint" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Field" Member="Field">
    <Type Name="Field">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Member="Pid" Storage="_pid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="istrue" Member="Istrue" Storage="_istrue" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="class" Member="Class" Storage="_class" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FieldInformation" Member="FieldInformation">
    <Type Name="FieldInformation">
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Field" Member="Field" Storage="_field" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Year" Member="Year" Storage="_year" Type="System.Int16" DbType="smallint" CanBeNull="true" />
      <Column Name="MiniField" Member="MiniField" Storage="_miniField" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="QinShi" Member="QinShi" Storage="_qinShi" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Field1" Member="Field1" Storage="_field1" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Field2" Member="Field2" Storage="_field2" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Association Name="FK_FieldInformation_Profile" Member="Profile" Storage="_profile" ThisKey="Userid" OtherKey="UserId" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Friend" Member="Friend">
    <Type Name="Friend">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="fromid" Member="Fromid" Storage="_fromid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="toid" Member="Toid" Storage="_toid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="IsTrue" Member="IsTrue" Storage="_isTrue" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCommon" Member="IsCommon" Storage="_isCommon" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Group" Member="Group">
    <Type Name="Group">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Member="GroupName" Storage="_groupName" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="summmary" Member="Summmary" Storage="_summmary" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateUserid" Member="CreateUserid" Storage="_createUserid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Publish" Member="Publish" Storage="_publish" Type="System.String" DbType="nvarchar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GroupClass" Member="GroupClass" Storage="_groupClass" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="AdminCount" Member="AdminCount" Storage="_adminCount" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Member="LogCount" Storage="_logCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Member="ViewCount" Storage="_viewCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="JoinLevel" Member="JoinLevel" Storage="_joinLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="ShowLevel" Member="ShowLevel" Storage="_showLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="UserCount" Member="UserCount" Storage="_userCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="MaxUserCount" Member="MaxUserCount" Storage="_maxUserCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="MagicBox" Member="MagicBox" Storage="_magicBox" Type="System.String" DbType="nvarchar(4000)" CanBeNull="true" />
      <Column Name="LogoUrl" Member="LogoUrl" Storage="_logoUrl" Type="System.String" DbType="nvarchar(250)" CanBeNull="true" />
      <Column Name="addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Num0" Member="Num0" Storage="_num0" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Other0" Member="Other0" Storage="_other0" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Other1" Member="Other1" Storage="_other1" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Other2" Member="Other2" Storage="_other2" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="IsTrue" Member="IsTrue" Storage="_isTrue" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="categoryid" Member="Categoryid" Storage="_categoryid" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Association Name="FK_GroupUser_Group" Member="GroupUserList" Storage="_groupUserList" ThisKey="Id" OtherKey="Groupid" Type="GroupUser" />
    </Type>
  </Table>
  <Table Name="dbo.GroupUser" Member="GroupUser">
    <Type Name="GroupUser">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Groupid" Member="Groupid" Storage="_groupid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Level" Member="Level" Storage="_level" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Member="AddTime" Storage="_addTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Member="LogCount" Storage="_logCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Class" Member="Class" Storage="_class" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="IsTrue" Member="IsTrue" Storage="_isTrue" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRss" Member="IsRss" Storage="_isRss" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Association Name="FK_GroupUser_Group" Member="Group" Storage="_group" ThisKey="Groupid" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Log" Member="LogTable">
    <Type Name="Log">
      <Column Name="Trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="body" Member="Body" Storage="_body" Type="System.String" DbType="ntext" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPost" Member="IsPost" Storage="_isPost" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="Anonymous" Member="Anonymous" Storage="_anonymous" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Member="AddTime" Storage="_addTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="EditTime" Member="EditTime" Storage="_editTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Member="ViewCount" Storage="_viewCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="PushCount" Member="PushCount" Storage="_pushCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="TrackBackCount" Member="TrackBackCount" Storage="_trackBackCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Member="CommentCount" Storage="_commentCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Member="GroupId" Storage="_groupId" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="LastCommentUserid" Member="LastCommentUserid" Storage="_lastCommentUserid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="LastCommentTime" Member="LastCommentTime" Storage="_lastCommentTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="istellme" Member="Istellme" Storage="_istellme" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Association Name="FK_LogTag_Log" Member="LogTagList" Storage="_logTagList" ThisKey="Id" OtherKey="Logid" Type="LogTag" />
      <Association Name="FK_Push_Log" Member="PushList" Storage="_pushList" ThisKey="Id" OtherKey="Logid" Type="Push" />
    </Type>
  </Table>
  <Table Name="dbo.LogTag" Member="LogTag">
    <Type Name="LogTag">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tagid" Member="Tagid" Storage="_tagid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="logid" Member="Logid" Storage="_logid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Association Name="FK_LogTag_Log" Member="Log" Storage="_log" ThisKey="Logid" OtherKey="Id" Type="Log" IsForeignKey="true" />
      <Association Name="FK_LogTag_Tags" Member="TagidTags" Storage="_tagidTags" ThisKey="Tagid" OtherKey="Id" Type="Tags" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Message">
    <Type Name="Message">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="FromId" Member="FromId" Storage="_fromId" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="ToId" Member="ToId" Storage="_toId" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Member="Body" Storage="_body" Type="System.String" DbType="nvarchar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SendTime" Member="SendTime" Storage="_sendTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="IsSee" Member="IsSee" Storage="_isSee" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsFromDel" Member="IsFromDel" Storage="_isFromDel" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsToDel" Member="IsToDel" Storage="_isToDel" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHtml" Member="IsHtml" Storage="_isHtml" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MiniField" Member="MiniField">
    <Type Name="MiniField">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pid" Member="Pid" Storage="_pid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="class" Member="Class" Storage="_class" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalInformation" Member="PersonalInformation">
    <Type Name="PersonalInformation">
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoveLike" Member="LoveLike" Storage="_loveLike" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveBook" Member="LoveBook" Storage="_loveBook" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveMusic" Member="LoveMusic" Storage="_loveMusic" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveMovie" Member="LoveMovie" Storage="_loveMovie" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveSports" Member="LoveSports" Storage="_loveSports" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveGame" Member="LoveGame" Storage="_loveGame" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="LoveComic" Member="LoveComic" Storage="_loveComic" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="JoinSociety" Member="JoinSociety" Storage="_joinSociety" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Association Name="FK_PersonalInformation_Profile" Member="Profile" Storage="_profile" ThisKey="Userid" OtherKey="UserId" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photos" Member="Photos">
    <Type Name="Photos">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Albumid" Member="Albumid" Storage="_albumid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Addtime" Member="Addtime" Storage="_addtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Path" Member="Path" Storage="_path" Type="System.String" DbType="nvarchar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Order" Member="Order" Storage="_order" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Member="CommentCount" Storage="_commentCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Profile" Member="Profile">
    <Type Name="Profile">
      <Column Name="UserId" Member="UserId" Storage="_userId" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShowText" Member="ShowText" Storage="_showText" Type="System.String" DbType="nvarchar(20)" CanBeNull="true" />
      <Column Name="ShowTextTime" Member="ShowTextTime" Storage="_showTextTime" Type="System.DateTime" DbType="smalldatetime" CanBeNull="true" />
      <Column Name="Score" Member="Score" Storage="_score" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="ShowScore" Member="ShowScore" Storage="_showScore" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="DelScore" Member="DelScore" Storage="_delScore" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="MagicBox" Member="MagicBox" Storage="_magicBox" Type="System.String" DbType="ntext NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FaceShowLevel" Member="FaceShowLevel" Storage="_faceShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="BasicInfoShowLevel" Member="BasicInfoShowLevel" Storage="_basicInfoShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="SchoolInfoShowLevel" Member="SchoolInfoShowLevel" Storage="_schoolInfoShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="ContactInfoShowLevel" Member="ContactInfoShowLevel" Storage="_contactInfoShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="PersonalInfoShowLevel" Member="PersonalInfoShowLevel" Storage="_personalInfoShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="AllShowLevel" Member="AllShowLevel" Storage="_allShowLevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="MessageAll" Member="MessageAll" Storage="_messageAll" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="MessageCount" Member="MessageCount" Storage="_messageCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="FileSizeAll" Member="FileSizeAll" Storage="_fileSizeAll" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="FileSizeCount" Member="FileSizeCount" Storage="_fileSizeCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="FriendAll" Member="FriendAll" Storage="_friendAll" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="FriendCount" Member="FriendCount" Storage="_friendCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="LogCount" Member="LogCount" Storage="_logCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Member="CommentCount" Storage="_commentCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="GroupCount" Member="GroupCount" Storage="_groupCount" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="IsMagicBox" Member="IsMagicBox" Storage="_isMagicBox" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Member="ViewCount" Storage="_viewCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Member="CreateTime" Storage="_createTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="IsStar" Member="IsStar" Storage="_isStar" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsUpdate" Member="IsUpdate" Storage="_isUpdate" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="Applications" Member="Applications" Storage="_applications" Type="System.String" DbType="varchar(4000)" CanBeNull="true" />
      <Column Name="Applicationlist" Member="Applicationlist" Storage="_applicationlist" Type="System.String" DbType="varchar(4000)" CanBeNull="true" />
      <Column Name="AlbumCount" Member="AlbumCount" Storage="_albumCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="field" Member="Field" Storage="_field" Type="System.Byte" DbType="tinyint" CanBeNull="true" />
      <Column Name="InField" Member="InField" Storage="_inField" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Association Name="FK_BasicInformation_Profile" Member="BasicInformation" Storage="_basicInformation" ThisKey="UserId" OtherKey="Userid" Type="BasicInformation" Cardinality="One" />
      <Association Name="FK_ContactInformation_Account" Member="ContactInformation" Storage="_contactInformation" ThisKey="UserId" OtherKey="Userid" Type="ContactInformation" Cardinality="One" />
      <Association Name="FK_FieldInformation_Profile" Member="FieldInformation" Storage="_fieldInformation" ThisKey="UserId" OtherKey="Userid" Type="FieldInformation" Cardinality="One" />
      <Association Name="FK_PersonalInformation_Profile" Member="PersonalInformation" Storage="_personalInformation" ThisKey="UserId" OtherKey="Userid" Type="PersonalInformation" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Province">
    <Type Name="Province">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Push" Member="Push">
    <Type Name="Push">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Logid" Member="Logid" Storage="_logid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="PushTime" Member="PushTime" Storage="_pushTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Association Name="FK_Push_Log" Member="Log" Storage="_log" ThisKey="Logid" OtherKey="Id" Type="Log" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QinShi" Member="QinShi">
    <Type Name="QinShi">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="QinShi" Member="QinShiMember" Storage="_qinShiMember" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="School" Member="School" Storage="_school" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="SchoolClass" Member="SchoolClass" Storage="_schoolClass" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="ServicesTable">
    <Type Name="Services">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="body" Member="Body" Storage="_body" Type="System.String" DbType="nvarchar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Member="Answer" Storage="_answer" Type="System.String" DbType="nvarchar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="status" Member="Status" Storage="_status" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="sendtime" Member="Sendtime" Storage="_sendtime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="Answertime" Member="Answertime" Storage="_answertime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Email" Member="Email" Storage="_email" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SuperNote" Member="SuperNote">
    <Type Name="SuperNote">
      <Column Name="trueid" Member="Trueid" Storage="_trueid" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="faceurl" Member="Faceurl" Storage="_faceurl" Type="System.String" DbType="nvarchar(500)" CanBeNull="true" />
      <Column Name="url" Member="Url" Storage="_url" Type="System.String" DbType="nvarchar(500) NOT NULL" CanBeNull="false" />
      <Column Name="description" Member="Description" Storage="_description" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="userid" Member="Userid" Storage="_userid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Member="ViewCount" Storage="_viewCount" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Member="AddTime" Storage="_addTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="showlevel" Member="Showlevel" Storage="_showlevel" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Column Name="systemcategory" Member="Systemcategory" Storage="_systemcategory" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="category" Member="Category" Storage="_category" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="type" Member="Type" Storage="_type" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tags">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Member="Title" Storage="_title" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Count" Member="Count" Storage="_count" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Storage="_type" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
      <Association Name="FK_LogTag_Tags" Member="TagidLogTagList" Storage="_tagidLogTagList" ThisKey="Id" OtherKey="Tagid" Type="LogTag" />
    </Type>
  </Table>
  <Table Name="dbo.ViewData" Member="ViewData">
    <Type Name="ViewData">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ownerid" Member="Ownerid" Storage="_ownerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Viewerid" Member="Viewerid" Storage="_viewerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="IpandComputer" Member="IpandComputer" Storage="_ipandComputer" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewPageUrl" Member="ViewPageUrl" Storage="_viewPageUrl" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LastUrl" Member="LastUrl" Storage="_lastUrl" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ViewTime" Member="ViewTime" Storage="_viewTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="ViewClass" Member="ViewClass" Storage="_viewClass" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>