<?xml version="1.0" encoding="utf-16"?>
<Database Name="CHSNSDB" EntityNamespace="CHSNS.Models" ContextNamespace="CHSNS.Models" Class="CHSNSDBContext" EntityBase="CHSNSEntity" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CHSNSDB;Integrated Security=True" SettingsObjectName="Properties.Settings" SettingsPropertyName="CHSNSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="ID" Member="ID" Storage="_iD" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nickname" Member="Nickname" Storage="_nickname" Type="System.String" DbType="nvarchar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Member="Email" Storage="_email" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Question" Member="Question" Storage="_question" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Answer" Member="Answer" Storage="_answer" Type="System.String" DbType="char(32)" CanBeNull="true" />
      <Column Name="Code" Member="Code" Storage="_code" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="LoginTime" Member="LoginTime" Storage="_loginTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="RegTime" Member="RegTime" Storage="_regTime" Type="System.DateTime" DbType="smalldatetime NOT NULL" CanBeNull="false" />
      <Column Name="TruePassword" Member="TruePassword" Storage="_truePassword" Type="System.String" DbType="char(32) NOT NULL" CanBeNull="false" />
      <Column Name="TrueEmail" Member="TrueEmail" Storage="_trueEmail" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Roles" Member="Roles" Storage="_roles" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Member="Password" Storage="_password" Type="System.String" DbType="char(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BaseInfo" Member="BaseInfo">
    <Type Name="BaseInfo">
      <Column Name="UserID" Member="UserID" Storage="_userID" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Name="Sex" Member="Sex" Storage="_sex" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="ProvinceID" Member="ProvinceID" Storage="_provinceID" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="CityID" Member="CityID" Storage="_cityID" Type="System.Int64" DbType="bigint" CanBeNull="true" />
      <Column Name="Birthday" Member="Birthday" Storage="_birthday" Type="System.DateTime" DbType="smalldatetime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="City">
    <Type Name="City">
      <Column Name="ID" Member="ID" Storage="_iD" Type="System.Int64" DbType="bigint NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinceID" Member="ProvinceID" Storage="_provinceID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HasApp" Member="HasApp">
    <Type Name="HasApp">
      <Column Name="ID" Member="ID" Storage="_iD" Type="System.Int64" DbType="bigint NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Member="UserID" Storage="_userID" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="AppName" Member="AppName" Storage="_appName" Type="System.String" DbType="nvarchar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TopMenu" Member="TopMenu" Storage="_topMenu" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="MyMenu" Member="MyMenu" Storage="_myMenu" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Province">
    <Type Name="Province">
      <Column Name="ID" Member="ID" Storage="_iD" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Member="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewData" Member="ViewData">
    <Type Name="ViewData">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Ownerid" Member="Ownerid" Storage="_ownerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="Viewerid" Member="Viewerid" Storage="_viewerid" Type="System.Int64" DbType="bigint NOT NULL" CanBeNull="false" />
      <Column Name="IpandComputer" Member="IpandComputer" Storage="_ipandComputer" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewPageUrl" Member="ViewPageUrl" Storage="_viewPageUrl" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LastUrl" Member="LastUrl" Storage="_lastUrl" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ViewTime" Member="ViewTime" Storage="_viewTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="ViewClass" Member="ViewClass" Storage="_viewClass" Type="System.Byte" DbType="tinyint NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>