//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CHSNS.Models
{
    public partial class ContactInformation
    {
        #region Primitive Properties
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string QQ
        {
            get;
            set;
        }
    
        public virtual string Msn
        {
            get;
            set;
        }
    
        public virtual string WangWang
        {
            get;
            set;
        }
    
        public virtual string NeteasePop
        {
            get;
            set;
        }
    
        public virtual string UC
        {
            get;
            set;
        }
    
        public virtual string Telphone
        {
            get;
            set;
        }
    
        public virtual string Mobiephone
        {
            get;
            set;
        }
    
        public virtual string WebSite
        {
            get;
            set;
        }
    
        public virtual byte TellMethod
        {
            get;
            set;
        }
    
        public virtual byte ShowLevel
        {
            get;
            set;
        }

        #endregion
    }
}
