//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CHSNS.Models
{
    public partial class Entry
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual string Url
        {
            get;
            set;
        }
    
        public virtual long CreaterId
        {
            get;
            set;
        }
    
        public virtual System.DateTime UpdateTime
        {
            get;
            set;
        }
    
        public virtual Nullable<long> CurrentId
        {
            get;
            set;
        }
    
        public virtual int EditCount
        {
            get;
            set;
        }
    
        public virtual long ViewCount
        {
            get;
            set;
        }
    
        public virtual int Status
        {
            get;
            set;
        }
    
        public virtual string Ext
        {
            get;
            set;
        }

        #endregion
    }
}
