//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CHSNS.Models
{
    public partial class FieldInformation
    {
        #region Primitive Properties
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual long Field
        {
            get;
            set;
        }
    
        public virtual Nullable<short> Year
        {
            get;
            set;
        }
    
        public virtual Nullable<long> MiniField
        {
            get;
            set;
        }
    
        public virtual Nullable<long> QinShi
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Field1
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Field2
        {
            get;
            set;
        }

        #endregion
    }
}
