//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CHSNS.Models
{
    public partial class Note
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Summary
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime EditTime
        {
            get;
            set;
        }
    
        public virtual byte Type
        {
            get;
            set;
        }
    
        public virtual long ParentId
        {
            get;
            set;
        }
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual byte IsTellMe
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsAnonymous
        {
            get;
            set;
        }
    
        public virtual byte ShowLevel
        {
            get;
            set;
        }
    
        public virtual long ViewCount
        {
            get;
            set;
        }
    
        public virtual long PushCount
        {
            get;
            set;
        }
    
        public virtual long TrackBackCount
        {
            get;
            set;
        }
    
        public virtual long CommentCount
        {
            get;
            set;
        }
    
        public virtual long LastCommentUserId
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastCommentTime
        {
            get;
            set;
        }
    
        public virtual string Ext
        {
            get;
            set;
        }

        #endregion
    }
}
