//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CHSNS.Models
{
    public partial class PersonalInformation
    {
        #region Primitive Properties
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual string LoveLike
        {
            get;
            set;
        }
    
        public virtual string LoveBook
        {
            get;
            set;
        }
    
        public virtual string LoveMusic
        {
            get;
            set;
        }
    
        public virtual string LoveMovie
        {
            get;
            set;
        }
    
        public virtual string LoveSports
        {
            get;
            set;
        }
    
        public virtual string LoveGame
        {
            get;
            set;
        }
    
        public virtual string LoveComic
        {
            get;
            set;
        }
    
        public virtual string JoinSociety
        {
            get;
            set;
        }

        #endregion
    }
}
