//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CHSNS.Models
{
    public partial class Profile
    {
        #region Primitive Properties
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Face
        {
            get;
            set;
        }
    
        public virtual int Status
        {
            get;
            set;
        }
    
        public virtual long Score
        {
            get;
            set;
        }
    
        public virtual long ShowScore
        {
            get;
            set;
        }
    
        public virtual long DelScore
        {
            get;
            set;
        }
    
        public virtual byte ShowLevel
        {
            get;
            set;
        }
    
        public virtual string MagicBox
        {
            get;
            set;
        }
    
        public virtual bool HasMagicBox
        {
            get;
            set;
        }
    
        public virtual System.DateTime RegTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime LoginTime
        {
            get;
            set;
        }
    
        public virtual long ViewCount
        {
            get;
            set;
        }
    
        public virtual long FileSizeAll
        {
            get;
            set;
        }
    
        public virtual long FileSizeCount
        {
            get;
            set;
        }
    
        public virtual string Applications
        {
            get;
            set;
        }
    
        public virtual string Applicationlist
        {
            get;
            set;
        }

        #endregion
    }
}
