//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CHSNS.Models
{
    public partial class Push
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual long LogId
        {
            get;
            set;
        }
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }

        #endregion
    }
}
