//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CHSNS.Models
{
    public partial class SuperNote
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string FaceURL
        {
            get;
            set;
        }
    
        public virtual string Url
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual long UserId
        {
            get;
            set;
        }
    
        public virtual long ViewCount
        {
            get;
            set;
        }
    
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        public virtual byte ShowLevel
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SystemCategory
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Category
        {
            get;
            set;
        }
    
        public virtual byte Type
        {
            get;
            set;
        }

        #endregion
    }
}
