//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MythBusters.Models
{
    public partial class MythBustersEntities1 : ObjectContext
    {
        public const string ConnectionString = "name=MythBustersEntities1";
        public const string ContainerName = "MythBustersEntities1";
    
        #region Constructors
    
        public MythBustersEntities1()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MythBustersEntities1(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MythBustersEntities1(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Profile> Profile
        {
            get { return _profile  ?? (_profile = CreateObjectSet<Profile>("Profile")); }
        }
        private ObjectSet<Profile> _profile;

        #endregion
    }
}
