
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace CHSNS.Models
{
    /// <summary>
    /// The class representing the dbo.HasApp table.
    /// </summary>
    [Table(Name="dbo.HasApp")]
    public partial class HasApp
        : CHSNSEntity
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="HasApp"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public HasApp()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _iD = default(long);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_iD", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    OnIDChanging(value);
                    OnPropertyChanging("ID");
                    _iD = value;
                    OnPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        
        private long _userID;

        /// <summary>
        /// Gets or sets the UserID column value.
        /// </summary>
        [Column(Name="UserID", Storage="_userID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    OnUserIDChanging(value);
                    OnPropertyChanging("UserID");
                    _userID = value;
                    OnPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        
        private string _appName;

        /// <summary>
        /// Gets or sets the AppName column value.
        /// </summary>
        [Column(Name="AppName", Storage="_appName", DbType="nvarchar(250) NOT NULL", CanBeNull=false)]
        public string AppName
        {
            get { return _appName; }
            set
            {
                if (_appName != value)
                {
                    OnAppNameChanging(value);
                    OnPropertyChanging("AppName");
                    _appName = value;
                    OnPropertyChanged("AppName");
                    OnAppNameChanged();
                }
            }
        }
        
        private bool _topMenu;

        /// <summary>
        /// Gets or sets the TopMenu column value.
        /// </summary>
        [Column(Name="TopMenu", Storage="_topMenu", DbType="bit NOT NULL", CanBeNull=false)]
        public bool TopMenu
        {
            get { return _topMenu; }
            set
            {
                if (_topMenu != value)
                {
                    OnTopMenuChanging(value);
                    OnPropertyChanging("TopMenu");
                    _topMenu = value;
                    OnPropertyChanged("TopMenu");
                    OnTopMenuChanged();
                }
            }
        }
        
        private bool _myMenu;

        /// <summary>
        /// Gets or sets the MyMenu column value.
        /// </summary>
        [Column(Name="MyMenu", Storage="_myMenu", DbType="bit NOT NULL", CanBeNull=false)]
        public bool MyMenu
        {
            get { return _myMenu; }
            set
            {
                if (_myMenu != value)
                {
                    OnMyMenuChanging(value);
                    OnPropertyChanging("MyMenu");
                    _myMenu = value;
                    OnPropertyChanged("MyMenu");
                    OnMyMenuChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(long value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when UserID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUserIDChanging(long value);
        /// <summary>Called after UserID has Changed.</summary>
        partial void OnUserIDChanged();
        /// <summary>Called when AppName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnAppNameChanging(string value);
        /// <summary>Called after AppName has Changed.</summary>
        partial void OnAppNameChanged();
        /// <summary>Called when TopMenu is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTopMenuChanging(bool value);
        /// <summary>Called after TopMenu has Changed.</summary>
        partial void OnTopMenuChanged();
        /// <summary>Called when MyMenu is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnMyMenuChanging(bool value);
        /// <summary>Called after MyMenu has Changed.</summary>
        partial void OnMyMenuChanged();
        #endregion
        
    }
}

