// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CHSNS.Controllers {
    public partial class EventController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EventController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EventController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetSystemTemplate() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetSystemTemplate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddSystemTemplate() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddSystemTemplate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EventController Actions { get { return MVC.Event; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "event";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = ("Index").ToLowerInvariant();
            public readonly string SystemTemplate = ("SystemTemplate").ToLowerInvariant();
            public readonly string GetSystemTemplate = ("GetSystemTemplate").ToLowerInvariant();
            public readonly string AddSystemTemplate = ("AddSystemTemplate").ToLowerInvariant();
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "~/Views/Event/Index.aspx";
            public readonly string Show = "~/Views/Event/Show.aspx";
            static readonly _Admin s_Admin = new _Admin();
            public _Admin Admin { get { return s_Admin; } }
            public partial class _Admin{
                public readonly string SystemTemplate = "~/Views/Event/Admin/SystemTemplate.ascx";
            }
            static readonly _IndexCtl s_IndexCtl = new _IndexCtl();
            public _IndexCtl IndexCtl { get { return s_IndexCtl; } }
            public partial class _IndexCtl{
                public readonly string Event = "~/Views/Event/IndexCtl/Event.ascx";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_EventController: CHSNS.Controllers.EventController {
        public T4MVC_EventController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SystemTemplate() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SystemTemplate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetSystemTemplate(string name) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetSystemTemplate);
            callInfo.RouteValueDictionary.Add("name", name);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddSystemTemplate(string c, string v, string t) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddSystemTemplate);
            callInfo.RouteValueDictionary.Add("c", c);
            callInfo.RouteValueDictionary.Add("v", v);
            callInfo.RouteValueDictionary.Add("t", t);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
